### ISSUE TITLE
GIMP 2.10.34 doesn't run in Ubuntu 20.04.6

### ISSUE THREAD

**Issue by brunoalvieira** [ivan-hc/GIMP-appimage#8] opened 2023-04-17 00:08 UTC
> /tmp/.mount_GIMP-xmrBhbv/AppRun: 8: export: ./usr/lib/x86_64-linux-gnu/libjson-c.so.5.1.0:/tmp/.mount_GIMP-xmrBhbv/usr/lib/x86_64-linux-gnu/libgimp-2.0.so.0.1000.34:/tmp/.mount_GIMP-xmrBhbv/usr/lib/x86_64-linux-gnu/libgimpui-2.0.so.0.1000.34: bad variable name`

**Comment by ivan-hc** [comment] 2023-04-17 23:53
I've found this https://github.com/PowerShell/PowerShell/issues/3525

As a solution they have changed `#!/bin/sh` to `#!/bin/bash` in the first line of the AppRun script

1. Extract the AppImage

        ./*AppImage --appimage-extract

2. To check if the problem is related to the ./squashfs-root/AppRun sctipt try to edit it with your favourite text editor
3. After this, enter the "squashfs-root" directory

        cd squashfs-root

and run the AppRun script

       ./AppRun

now it should work. If so, I'll consider to edit the AppRun just uploaded on this repository as a separate element, at https://github.com/ivan-hc/GIMP-appimage/blob/main/AppRun

**Comment by ivan-hc** [comment] 2023-07-07 04:08
No answer, I close this issue

**Closed by ivan-hc** 2023-07-07 04:08 UTC
